version: '3.8'

services:
  pg:
    image: postgres
    environment:
      POSTGRES_DB: cargo
      POSTGRES_USER: Arseniy
      POSTGRES_PASSWORD: 12345
    ports:
      - "5434:5432"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: cargo_logs
    ports:
      - "9092:9092"

  # fastapi_app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - pg
  #   ports:
  #     - "8000:8000"