"""Not unique title in rate

Revision ID: e3a935dd898a
Revises: bf9794caeffc
Create Date: 2024-12-02 01:13:56.772726

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e3a935dd898a"
down_revision: Union[str, None] = "bf9794caeffc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_rates_title", "rates", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_rates_title", "rates", ["title"])
    # ### end Alembic commands ###
