"""add date of action to rate

Revision ID: bf9794caeffc
Revises: 17890e19061a
Create Date: 2024-12-02 00:15:49.055191

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "bf9794caeffc"
down_revision: Union[str, None] = "17890e19061a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "rates", sa.Column("date_of_action", sa.Date(), nullable=False)
    )
    op.alter_column(
        "rates",
        "value",
        existing_type=sa.INTEGER(),
        type_=sa.Float(),
        existing_nullable=False,
    )
    op.create_unique_constraint(op.f("uq_rates_title"), "rates", ["title"])
    op.drop_column("rates", "time_created")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "rates",
        sa.Column(
            "time_created",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(op.f("uq_rates_title"), "rates", type_="unique")
    op.alter_column(
        "rates",
        "value",
        existing_type=sa.Float(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.drop_column("rates", "date_of_action")
    # ### end Alembic commands ###
